management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  thirdPartyProperties:
    #kelvin	celsius	fahrenheit
    temperatureUnit: celsius
    cacheClearSchedule: "*/3 * * * * *"
    weatherstack:
      apiKey:
      enable: Y
      sequence: 0
    openWeatherMap:
      apiKey:
      enable: Y
      sequence: 1


logging:
  config: classpath:logback-local.xml

server:
  port: 8080
  tomcat:
    threads:
      max: 100
