management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  thirdPartyProperties:
    #kelvin	celsius	fahrenheit
    temperatureUnit: celsius
    cacheClearSchedule: "*/3 * * * * *"
    weatherstack:
      apiKey: 231331da0f85386b47bce1d937502623
      enable: Y
      sequence: 0
    openWeatherMap:
      apiKey: aa5b776dc6b821ab12ed4dd6da495d60
      enable: Y
      sequence: 1


logging:
  config: classpath:logback-local.xml

server:
  port: 8080
  tomcat:
    threads:
      max: 100
